const mongoose = require("mongoose"); // requirng Mongoose to access Mongoose model classes
const requireLogin = require("../middlewares/requireLogin.js"); // to make sure user is logged in
const requireCredits = require("../middlewares/requireCredits.js"); // to make sure that user has enough credits

const Survey = mongoose.model("surveys");

module.exports = app => {
  app.post("/api/surveys", requireLogin, requireCredits, (req, res) => {
    const { title, subject, body, recipients } = req.body;
    const survey = new Survey({
      title, // ES2016 - title: title
      subject,
      body,
      recipients: recipients.split(",").map(email => ({ email: email.trim() })), // email is now an array of objects instead of an array of strings
      _user: req.user.id, // autogenerated by Mongoose in MongoDB
      dateSent: Date.now()
    });
  });
};
